[package]
name = "docker-restarter"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
bollard = "0.18"
futures-util = "0.3"
env_logger = "0.11"
log = "0.4"
clap = { version = "4.2", features = ["derive"] }
