services:
  app:
    build:
      context: .
    environment:
      - RUST_LOG=info
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Access Docker socket for control
    command: --watch logger --restart logger --pattern hello_world --skip-first=true

  logger:
    image: bash # Uses a lightweight bash image
    container_name: logger
    volumes:
      - ./script.sh:/script.sh
    entrypoint: [ "/bin/sh", "/script.sh" ]
