services:
  # app:
  #   build:
  #     context: . # Build the Rust restarter service from the current directory
  #   environment:
  #     - RUST_LOG=info
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock # Access Docker socket for control
  #   command: --watch logger --restart logger --pattern hello_world --count 2

  logger:
    image: bash # Uses a lightweight bash image
    container_name: logger
    volumes:
      - ./script.sh:/script.sh
    entrypoint: [ "/bin/sh", "/script.sh" ]
